name: dragon_mat
isMaterial: true

####network#####
network: material
database_name: tensoSDF/dragon
mesh: data/meshes/dragon_occ_shape-100000.ply
geo_model_path: data/model/dragon_occ_shape/model.pth
split_manul: true
nerfDataType: true

reg_diffuse_light: true
reg_diffuse_light_lambda: 0.1
reg_mat: true
shader_cfg:
  diffuse_sample_num: 512
  specular_sample_num: 256
  outer_light_version: envlight
  light_exp_max: 5.0
  inner_light_exp_max: 5.0
  human_lights: false

######loss######
loss: ['nerf_render','mat_reg', 'nis']
val_metric: ['mat_render']
key_metric_name: psnr_nis

####dataset#####
train_dataset_type: dummy
dataset_dir: nerf_data/tensoSDF           # !!!! change your dataset dir !!!!
train_dataset_cfg:
  database_name: tensoSDF/dragon
val_set_list:
  -
    name: val
    type: dummy
    cfg:
      database_name: tensoSDF/dragon

####trainier####
optimizer_type: adam
lr_type: warm_up_cos
total_step: 100000
val_interval: 5000
save_interval: 5000
train_log_step: 10

####relighting settings####
albedoRescale: 2    # 0: don't rescale, 1: apply single rescaling, 2: apply three rescaling
trans: false